"""Prove on the organizer data that incremental silver equals a full rebuild (ADR-028).

Holds back the last days of every fact table, runs the pipeline, delivers the held-back days, runs it again
incrementally (timed), copies silver, rebuilds everything from the same bronze (timed) and compares every silver and
quarantine table row by row.

    python -m dispute_ops.pipeline.incremental_proof --raw ../data/raw --work /tmp/proof --hold-back-from 2026-06-11
"""

from __future__ import annotations

import argparse
import re
import shutil
import time
from datetime import date, datetime
from pathlib import Path

import duckdb

from dispute_ops.pipeline.contracts import CONTRACTS, ORDER
from dispute_ops.pipeline.layers import run_pipeline

ROOT = Path(__file__).resolve().parents[4]
PART = re.compile(r"year=(\d{4})/month=(\d{2})/day=(\d{2})")


def _link_tree(raw: Path, dst: Path, keep) -> int:
    n = 0
    for name in ORDER:
        for f in raw.glob(CONTRACTS[name].source):
            if keep(f):
                target = dst / f.relative_to(raw)
                if not target.exists():
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.symlink_to(f.resolve())
                    n += 1
    return n


def _day(f: Path) -> date | None:
    m = PART.search(str(f))
    return date(int(m[1]), int(m[2]), int(m[3])) if m else None


def compare(a: Path, b: Path) -> list[tuple[str, int, int, int, int]]:
    out = []
    files = sorted({p.relative_to(a) for p in a.rglob("*.parquet")} | {p.relative_to(b) for p in b.rglob("*.parquet")})
    con = duckdb.connect()
    for f in files:
        fa, fb = a / f, b / f
        if not (fa.exists() and fb.exists()):
            out.append((str(f), -1, -1, -1, -1))
            continue
        na = con.execute(f"SELECT count(*) FROM read_parquet('{fa}')").fetchone()[0]
        nb = con.execute(f"SELECT count(*) FROM read_parquet('{fb}')").fetchone()[0]
        ab = con.execute(f"SELECT count(*) FROM (SELECT * FROM read_parquet('{fa}') EXCEPT ALL SELECT * FROM read_parquet('{fb}'))").fetchone()[0]
        ba = con.execute(f"SELECT count(*) FROM (SELECT * FROM read_parquet('{fb}') EXCEPT ALL SELECT * FROM read_parquet('{fa}'))").fetchone()[0]
        out.append((str(f), na, nb, ab, ba))
    return out


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--raw", default=str(ROOT / "data" / "raw"))
    p.add_argument("--work", required=True)
    p.add_argument("--hold-back-from", default="2026-06-11")
    p.add_argument("--as-of", default="2026-06-17T12:00:00+00:00")
    p.add_argument("--report", default=str(ROOT / "docs" / "analysis" / "incremental-silver.md"))
    a = p.parse_args()
    raw, work, cut = Path(a.raw), Path(a.work), date.fromisoformat(a.hold_back_from)
    as_of = datetime.fromisoformat(a.as_of)
    if work.exists():
        shutil.rmtree(work)
    split, out = work / "raw", work / "out"
    first_files = _link_tree(raw, split, lambda f: (_day(f) or date.min) < cut)
    t0 = time.perf_counter()
    m1 = run_pipeline(split, out, as_of)
    t_first = time.perf_counter() - t0
    later_files = _link_tree(raw, split, lambda f: (_day(f) or date.min) >= cut)
    t0 = time.perf_counter()
    m2 = run_pipeline(split, out, as_of)
    t_inc = time.perf_counter() - t0
    shutil.copytree(out / "silver", work / "silver_incremental")
    t0 = time.perf_counter()
    m3 = run_pipeline(split, out, as_of, full=True)
    t_full = time.perf_counter() - t0
    rows = compare(work / "silver_incremental", out / "silver")
    identical = all(r[3] == 0 and r[4] == 0 and r[1] == r[2] for r in rows)

    lines = [
        "# Incremental silver equals a full rebuild — organizer data", "",
        f"Generated by `python -m dispute_ops.pipeline.incremental_proof` (ADR-028). Every fact partition dated "
        f"{cut} or later was held back ({later_files} files), the pipeline ran on the rest ({first_files} files), the "
        "held-back days were delivered and the pipeline ran again **incrementally**; then silver was rebuilt **in full** "
        "from the same bronze and the two were compared row by row (`EXCEPT ALL` both ways, every column).", "",
        f"**Result: {'identical' if identical else 'DIFFERENT'}** — "
        f"{sum(r[1] for r in rows if r[1] > 0):,} rows in {len(rows)} silver and quarantine tables.", "",
        "| Table | rows (incremental) | rows (full) | only in incremental | only in full |", "|---|---|---|---|---|",
        *[f"| {r[0]} | {r[1]:,} | {r[2]:,} | {r[3]} | {r[4]} |" for r in rows], "",
        "## Cost", "",
        "| Run | Status | Seconds | Keys recomputed (transactions) |", "|---|---|---|---|",
        f"| first delivery (full by construction) | {m1['status']} | {t_first:.1f} | all |",
        f"| held-back days, incremental | {m2['status']} | {t_inc:.1f} | {m2['tables']['transactions']['mode']} |",
        f"| same bronze, full rebuild | {m3['status']} | {t_full:.1f} | all |", "",
        "Per-step seconds (incremental run): " + ", ".join(f"{k} {v}" for k, v in m2["seconds"].items()) + ".", "",
        "The incremental run still rewrites each silver file (one Parquet per table); what it saves is the recomputation "
        "of untouched keys. At this size both take seconds; past ~100M rows silver would be partitioned so that only "
        "the touched partitions are rewritten.",
    ]
    Path(a.report).write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    if not identical:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
